/**
 * This class is generated by jOOQ
 */
package com.izhaoyan.jooq2.domain.tables;


import com.izhaoyan.jooq2.domain.Library;
import com.izhaoyan.jooq2.domain.tables.records.BookToBookStoreRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookToBookStore extends TableImpl<BookToBookStoreRecord> {

	private static final long serialVersionUID = 2129631904;

	/**
	 * The reference instance of <code>library.book_to_book_store</code>
	 */
	public static final BookToBookStore BOOK_TO_BOOK_STORE = new BookToBookStore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<BookToBookStoreRecord> getRecordType() {
		return BookToBookStoreRecord.class;
	}

	/**
	 * The column <code>library.book_to_book_store.book_store_name</code>.
	 */
	public final TableField<BookToBookStoreRecord, String> BOOK_STORE_NAME = createField("book_store_name", org.jooq.impl.SQLDataType.VARCHAR.length(400).nullable(false), this, "");

	/**
	 * The column <code>library.book_to_book_store.book_id</code>.
	 */
	public final TableField<BookToBookStoreRecord, Integer> BOOK_ID = createField("book_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>library.book_to_book_store.stock</code>.
	 */
	public final TableField<BookToBookStoreRecord, Integer> STOCK = createField("stock", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>library.book_to_book_store</code> table reference
	 */
	public BookToBookStore() {
		this("book_to_book_store", null);
	}

	/**
	 * Create an aliased <code>library.book_to_book_store</code> table reference
	 */
	public BookToBookStore(String alias) {
		this(alias, BOOK_TO_BOOK_STORE);
	}

	private BookToBookStore(String alias, Table<BookToBookStoreRecord> aliased) {
		this(alias, aliased, null);
	}

	private BookToBookStore(String alias, Table<BookToBookStoreRecord> aliased, Field<?>[] parameters) {
		super(alias, Library.LIBRARY, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public BookToBookStore as(String alias) {
		return new BookToBookStore(alias, this);
	}

	/**
	 * Rename this table
	 */
	public BookToBookStore rename(String name) {
		return new BookToBookStore(name, null);
	}
}
